
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'ru' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    'welcome.title': 'Bem-vindo ao TimeTracker',
    'welcome.hero.title': 'Transparência Total em Projetos',
    'welcome.hero.subtitle': 'Uma interface independente para visualizar atividades de projetos do SolidTime',
    'welcome.hero.description': 'Este aplicativo é uma iniciativa independente do SolidTime. É uma página/app com o objetivo de transparentar as atividades de projetos para clientes.',
    'welcome.features.title': 'Principais Funcionalidades',
    'welcome.about.title': 'Sobre o Projeto',
    'welcome.about.description': 'Esta é uma interface independente criada para fornecer transparência total das atividades de projetos aos clientes.',
    'welcome.about.solidtime': 'Baseado no SolidTime, oferece uma visão clara e organizada do progresso dos projetos.',
    'welcome.footer': 'Interface independente para SolidTime - Transparência em projetos',
    'get.started': 'Começar',
    'feature.transparency.title': 'Transparência Total',
    'feature.transparency.description': 'Visibilidade completa das atividades do projeto',
    'feature.timetracking.title': 'Controle de Tempo',
    'feature.timetracking.description': 'Acompanhamento preciso do tempo gasto',
    'feature.analytics.title': 'Análises Detalhadas',
    'feature.analytics.description': 'Relatórios e métricas de desempenho',
    'feature.clients.title': 'Portal do Cliente',
    'feature.clients.description': 'Interface dedicada para clientes',
    'feature.security.title': 'Segurança',
    'feature.security.description': 'Proteção de dados garantida',
    'feature.realtime.title': 'Tempo Real',
    'feature.realtime.description': 'Atualizações instantâneas',
    'projects': 'Projetos',
    'logout': 'Sair',
    'setup.title': 'Configuração',
    'setup.description': 'Configure sua conexão',
    'setup.url.label': 'URL do SolidTime',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'Token de API',
    'setup.token.placeholder': 'Seu token de API',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'loading': 'Carregando...',
    'error.generic': 'Ocorreu um erro',
    'error.retry': 'Tentar novamente',
    'no.projects': 'Nenhum projeto encontrado',
    'no.activity': 'Nenhuma atividade encontrada',
    'time.entries.title': 'Entradas de Tempo',
    'time.entries.subtitle': 'Visualize todas as entradas de tempo do projeto',
    'time.entries.back': 'Voltar ao Projeto',
    'total.hours': 'Total de Horas',
    'days.with.records': 'Dias com Registros',
    'total.records': 'Total de Registros',
    'activity.development': 'Desenvolvimento de Atividades',
    'activity.timeline': 'Linha do Tempo',
    'project.details': 'Detalhes do Projeto',
    'project.overview': 'Visão Geral',
    'view.time.entries': 'Ver Entradas de Tempo',
    'daily.hours': 'Horas Diárias',
    'weekly.overview': 'Visão Semanal',
    'team.activity': 'Atividade da Equipe',
    'latest.tasks': 'Tarefas Recentes',
    'enter.password': 'Digite a senha',
    'password': 'Senha',
    'access.project': 'Acessar Projeto',
    'invalid.password': 'Senha inválida',
    'day.details': 'Detalhes do Dia',
    'close': 'Fechar',
    'hours': 'horas',
    'task': 'Tarefa',
    'duration': 'Duração',
    'description': 'Descrição',
    'client': 'Cliente',
    'start.time': 'Hora de Início',
    'end.time': 'Hora de Fim'
  },
  en: {
    'welcome.title': 'Welcome to TimeTracker',
    'welcome.hero.title': 'Total Project Transparency',
    'welcome.hero.subtitle': 'An independent interface to view SolidTime project activities',
    'welcome.hero.description': 'This app is an independent initiative from SolidTime. It\'s a page/app aimed at providing transparency of project activities to clients.',
    'welcome.features.title': 'Key Features',
    'welcome.about.title': 'About the Project',
    'welcome.about.description': 'This is an independent interface created to provide total transparency of project activities to clients.',
    'welcome.about.solidtime': 'Based on SolidTime, it offers a clear and organized view of project progress.',
    'welcome.footer': 'Independent interface for SolidTime - Project transparency',
    'get.started': 'Get Started',
    'feature.transparency.title': 'Total Transparency',
    'feature.transparency.description': 'Complete visibility of project activities',
    'feature.timetracking.title': 'Time Tracking',
    'feature.timetracking.description': 'Precise tracking of time spent',
    'feature.analytics.title': 'Detailed Analytics',
    'feature.analytics.description': 'Performance reports and metrics',
    'feature.clients.title': 'Client Portal',
    'feature.clients.description': 'Dedicated interface for clients',
    'feature.security.title': 'Security',
    'feature.security.description': 'Guaranteed data protection',
    'feature.realtime.title': 'Real Time',
    'feature.realtime.description': 'Instant updates',
    'projects': 'Projects',
    'logout': 'Logout',
    'setup.title': 'Setup',
    'setup.description': 'Configure your connection',
    'setup.url.label': 'SolidTime URL',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'API Token',
    'setup.token.placeholder': 'Your API token',
    'save': 'Save',
    'cancel': 'Cancel',
    'loading': 'Loading...',
    'error.generic': 'An error occurred',
    'error.retry': 'Try again',
    'no.projects': 'No projects found',
    'no.activity': 'No activity found',
    'time.entries.title': 'Time Entries',
    'time.entries.subtitle': 'View all project time entries',
    'time.entries.back': 'Back to Project',
    'total.hours': 'Total Hours',
    'days.with.records': 'Days with Records',
    'total.records': 'Total Records',
    'activity.development': 'Activity Development',
    'activity.timeline': 'Timeline',
    'project.details': 'Project Details',
    'project.overview': 'Overview',
    'view.time.entries': 'View Time Entries',
    'daily.hours': 'Daily Hours',
    'weekly.overview': 'Weekly Overview',
    'team.activity': 'Team Activity',
    'latest.tasks': 'Latest Tasks',
    'enter.password': 'Enter password',
    'password': 'Password',
    'access.project': 'Access Project',
    'invalid.password': 'Invalid password',
    'day.details': 'Day Details',
    'close': 'Close',
    'hours': 'hours',
    'task': 'Task',
    'duration': 'Duration',
    'description': 'Description',
    'client': 'Client',
    'start.time': 'Start Time',
    'end.time': 'End Time'
  },
  es: {
    'welcome.title': 'Bienvenido a TimeTracker',
    'welcome.hero.title': 'Transparencia Total de Proyectos',
    'welcome.hero.subtitle': 'Una interfaz independiente para ver las actividades de proyectos de SolidTime',
    'welcome.hero.description': 'Esta aplicación es una iniciativa independiente de SolidTime. Es una página/app con el objetivo de transparentar las actividades de proyectos para clientes.',
    'welcome.features.title': 'Características Principales',
    'welcome.about.title': 'Sobre el Proyecto',
    'welcome.about.description': 'Esta es una interfaz independiente creada para proporcionar transparencia total de las actividades del proyecto a los clientes.',
    'welcome.about.solidtime': 'Basado en SolidTime, ofrece una vista clara y organizada del progreso del proyecto.',
    'welcome.footer': 'Interfaz independiente para SolidTime - Transparencia de proyectos',
    'get.started': 'Comenzar',
    'feature.transparency.title': 'Transparencia Total',
    'feature.transparency.description': 'Visibilidad completa de las actividades del proyecto',
    'feature.timetracking.title': 'Seguimiento de Tiempo',
    'feature.timetracking.description': 'Seguimiento preciso del tiempo invertido',
    'feature.analytics.title': 'Análisis Detallados',
    'feature.analytics.description': 'Informes y métricas de rendimiento',
    'feature.clients.title': 'Portal del Cliente',
    'feature.clients.description': 'Interfaz dedicada para clientes',
    'feature.security.title': 'Seguridad',
    'feature.security.description': 'Protección de datos garantizada',
    'feature.realtime.title': 'Tiempo Real',
    'feature.realtime.description': 'Actualizaciones instantáneas',
    'projects': 'Proyectos',
    'logout': 'Cerrar Sesión',
    'setup.title': 'Configuración',
    'setup.description': 'Configure su conexión',
    'setup.url.label': 'URL de SolidTime',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'Token de API',
    'setup.token.placeholder': 'Su token de API',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'loading': 'Cargando...',
    'error.generic': 'Ocurrió un error',
    'error.retry': 'Intentar de nuevo',
    'no.projects': 'No se encontraron proyectos',
    'no.activity': 'No se encontró actividad',
    'time.entries.title': 'Entradas de Tiempo',
    'time.entries.subtitle': 'Ver todas las entradas de tiempo del proyecto',
    'time.entries.back': 'Volver al Proyecto',
    'total.hours': 'Horas Totales',
    'days.with.records': 'Días con Registros',
    'total.records': 'Registros Totales',
    'activity.development': 'Desarrollo de Actividades',
    'activity.timeline': 'Línea de Tiempo',
    'project.details': 'Detalles del Proyecto',
    'project.overview': 'Resumen',
    'view.time.entries': 'Ver Entradas de Tiempo',
    'daily.hours': 'Horas Diarias',
    'weekly.overview': 'Resumen Semanal',
    'team.activity': 'Actividad del Equipo',
    'latest.tasks': 'Tareas Recientes',
    'enter.password': 'Ingrese la contraseña',
    'password': 'Contraseña',
    'access.project': 'Acceder al Proyecto',
    'invalid.password': 'Contraseña inválida',
    'day.details': 'Detalles del Día',
    'close': 'Cerrar',
    'hours': 'horas',
    'task': 'Tarea',
    'duration': 'Duración',
    'description': 'Descripción',
    'client': 'Cliente',
    'start.time': 'Hora de Inicio',
    'end.time': 'Hora de Fin'
  },
  fr: {
    'welcome.title': 'Bienvenue dans TimeTracker',
    'welcome.hero.title': 'Transparence Totale des Projets',
    'welcome.hero.subtitle': 'Une interface indépendante pour voir les activités de projet SolidTime',
    'welcome.hero.description': 'Cette application est une initiative indépendante de SolidTime. C\'est une page/app visant à transparenter les activités de projets pour les clients.',
    'welcome.features.title': 'Fonctionnalités Clés',
    'welcome.about.title': 'À Propos du Projet',
    'welcome.about.description': 'Il s\'agit d\'une interface indépendante créée pour fournir une transparence totale des activités de projet aux clients.',
    'welcome.about.solidtime': 'Basé sur SolidTime, il offre une vue claire et organisée du progrès du projet.',
    'welcome.footer': 'Interface indépendante pour SolidTime - Transparence des projets',
    'get.started': 'Commencer',
    'feature.transparency.title': 'Transparence Totale',
    'feature.transparency.description': 'Visibilité complète des activités du projet',
    'feature.timetracking.title': 'Suivi du Temps',
    'feature.timetracking.description': 'Suivi précis du temps passé',
    'feature.analytics.title': 'Analyses Détaillées',
    'feature.analytics.description': 'Rapports et métriques de performance',
    'feature.clients.title': 'Portail Client',
    'feature.clients.description': 'Interface dédiée aux clients',
    'feature.security.title': 'Sécurité',
    'feature.security.description': 'Protection des données garantie',
    'feature.realtime.title': 'Temps Réel',
    'feature.realtime.description': 'Mises à jour instantanées',
    'projects': 'Projets',
    'logout': 'Déconnexion',
    'setup.title': 'Configuration',
    'setup.description': 'Configurez votre connexion',
    'setup.url.label': 'URL SolidTime',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'Token API',
    'setup.token.placeholder': 'Votre token API',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'loading': 'Chargement...',
    'error.generic': 'Une erreur s\'est produite',
    'error.retry': 'Réessayer',
    'no.projects': 'Aucun projet trouvé',
    'no.activity': 'Aucune activité trouvée',
    'time.entries.title': 'Entrées de Temps',
    'time.entries.subtitle': 'Voir toutes les entrées de temps du projet',
    'time.entries.back': 'Retour au Projet',
    'total.hours': 'Heures Totales',
    'days.with.records': 'Jours avec Enregistrements',
    'total.records': 'Enregistrements Totaux',
    'activity.development': 'Développement d\'Activités',
    'activity.timeline': 'Chronologie',
    'project.details': 'Détails du Projet',
    'project.overview': 'Aperçu',
    'view.time.entries': 'Voir les Entrées de Temps',
    'daily.hours': 'Heures Quotidiennes',
    'weekly.overview': 'Aperçu Hebdomadaire',
    'team.activity': 'Activité de l\'Équipe',
    'latest.tasks': 'Tâches Récentes',
    'enter.password': 'Entrez le mot de passe',
    'password': 'Mot de passe',
    'access.project': 'Accéder au Projet',
    'invalid.password': 'Mot de passe invalide',
    'day.details': 'Détails du Jour',
    'close': 'Fermer',
    'hours': 'heures',
    'task': 'Tâche',
    'duration': 'Durée',
    'description': 'Description',
    'client': 'Client',
    'start.time': 'Heure de Début',
    'end.time': 'Heure de Fin'
  },
  de: {
    'welcome.title': 'Willkommen bei TimeTracker',
    'welcome.hero.title': 'Totale Projekttransparenz',
    'welcome.hero.subtitle': 'Eine unabhängige Schnittstelle zur Anzeige von SolidTime-Projektaktivitäten',
    'welcome.hero.description': 'Diese App ist eine unabhängige Initiative von SolidTime. Es ist eine Seite/App mit dem Ziel, Projektaktivitäten für Kunden transparent zu machen.',
    'welcome.features.title': 'Hauptfunktionen',
    'welcome.about.title': 'Über das Projekt',
    'welcome.about.description': 'Dies ist eine unabhängige Schnittstelle, die erstellt wurde, um Kunden totale Transparenz der Projektaktivitäten zu bieten.',
    'welcome.about.solidtime': 'Basierend auf SolidTime bietet es eine klare und organisierte Sicht auf den Projektfortschritt.',
    'welcome.footer': 'Unabhängige Schnittstelle für SolidTime - Projekttransparenz',
    'get.started': 'Loslegen',
    'feature.transparency.title': 'Totale Transparenz',
    'feature.transparency.description': 'Vollständige Sichtbarkeit der Projektaktivitäten',
    'feature.timetracking.title': 'Zeiterfassung',
    'feature.timetracking.description': 'Präzise Verfolgung der verbrachten Zeit',
    'feature.analytics.title': 'Detaillierte Analysen',
    'feature.analytics.description': 'Leistungsberichte und Metriken',
    'feature.clients.title': 'Kundenportal',
    'feature.clients.description': 'Dedizierte Schnittstelle für Kunden',
    'feature.security.title': 'Sicherheit',
    'feature.security.description': 'Garantierter Datenschutz',
    'feature.realtime.title': 'Echtzeit',
    'feature.realtime.description': 'Sofortige Updates',
    'projects': 'Projekte',
    'logout': 'Abmelden',
    'setup.title': 'Einrichtung',
    'setup.description': 'Konfigurieren Sie Ihre Verbindung',
    'setup.url.label': 'SolidTime URL',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'API Token',
    'setup.token.placeholder': 'Ihr API Token',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'loading': 'Wird geladen...',
    'error.generic': 'Ein Fehler ist aufgetreten',
    'error.retry': 'Erneut versuchen',
    'no.projects': 'Keine Projekte gefunden',
    'no.activity': 'Keine Aktivität gefunden',
    'time.entries.title': 'Zeiteinträge',
    'time.entries.subtitle': 'Alle Projektzeiteinträge anzeigen',
    'time.entries.back': 'Zurück zum Projekt',
    'total.hours': 'Gesamtstunden',
    'days.with.records': 'Tage mit Aufzeichnungen',
    'total.records': 'Gesamte Aufzeichnungen',
    'activity.development': 'Aktivitätsentwicklung',
    'activity.timeline': 'Zeitachse',
    'project.details': 'Projektdetails',
    'project.overview': 'Übersicht',
    'view.time.entries': 'Zeiteinträge anzeigen',
    'daily.hours': 'Tägliche Stunden',
    'weekly.overview': 'Wöchentliche Übersicht',
    'team.activity': 'Teamaktivität',
    'latest.tasks': 'Neueste Aufgaben',
    'enter.password': 'Passwort eingeben',
    'password': 'Passwort',
    'access.project': 'Projekt zugreifen',
    'invalid.password': 'Ungültiges Passwort',
    'day.details': 'Tagesdetails',
    'close': 'Schließen',
    'hours': 'Stunden',
    'task': 'Aufgabe',
    'duration': 'Dauer',
    'description': 'Beschreibung',
    'client': 'Kunde',
    'start.time': 'Startzeit',
    'end.time': 'Endzeit'
  },
  ru: {
    'welcome.title': 'Добро пожаловать в TimeTracker',
    'welcome.hero.title': 'Полная Прозрачность Проектов',
    'welcome.hero.subtitle': 'Независимый интерфейс для просмотра активности проектов SolidTime',
    'welcome.hero.description': 'Это приложение - независимая инициатива от SolidTime. Это страница/приложение с целью обеспечить прозрачность проектной деятельности для клиентов.',
    'welcome.features.title': 'Ключевые Функции',
    'welcome.about.title': 'О Проекте',
    'welcome.about.description': 'Это независимый интерфейс, созданный для обеспечения полной прозрачности проектной деятельности для клиентов.',
    'welcome.about.solidtime': 'Основанный на SolidTime, он предлагает четкий и организованный взгляд на прогресс проекта.',
    'welcome.footer': 'Независимый интерфейс для SolidTime - Прозрачность проектов',
    'get.started': 'Начать',
    'feature.transparency.title': 'Полная Прозрачность',
    'feature.transparency.description': 'Полная видимость активности проекта',
    'feature.timetracking.title': 'Учет Времени',
    'feature.timetracking.description': 'Точное отслеживание потраченного времени',
    'feature.analytics.title': 'Подробная Аналитика',
    'feature.analytics.description': 'Отчеты о производительности и метрики',
    'feature.clients.title': 'Портал Клиента',
    'feature.clients.description': 'Выделенный интерфейс для клиентов',
    'feature.security.title': 'Безопасность',
    'feature.security.description': 'Гарантированная защита данных',
    'feature.realtime.title': 'Реальное Время',
    'feature.realtime.description': 'Мгновенные обновления',
    'projects': 'Проекты',
    'logout': 'Выйти',
    'setup.title': 'Настройка',
    'setup.description': 'Настройте ваше соединение',
    'setup.url.label': 'URL SolidTime',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'API Токен',
    'setup.token.placeholder': 'Ваш API токен',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'loading': 'Загрузка...',
    'error.generic': 'Произошла ошибка',
    'error.retry': 'Попробовать снова',
    'no.projects': 'Проекты не найдены',
    'no.activity': 'Активность не найдена',
    'time.entries.title': 'Записи Времени',
    'time.entries.subtitle': 'Просмотреть все записи времени проекта',
    'time.entries.back': 'Вернуться к Проекту',
    'total.hours': 'Общие Часы',
    'days.with.records': 'Дни с Записями',
    'total.records': 'Общие Записи',
    'activity.development': 'Разработка Активности',
    'activity.timeline': 'Временная Шкала',
    'project.details': 'Детали Проекта',
    'project.overview': 'Обзор',
    'view.time.entries': 'Просмотреть Записи Времени',
    'daily.hours': 'Ежедневные Часы',
    'weekly.overview': 'Еженедельный Обзор',
    'team.activity': 'Активность Команды',
    'latest.tasks': 'Последние Задачи',
    'enter.password': 'Введите пароль',
    'password': 'Пароль',
    'access.project': 'Доступ к Проекту',
    'invalid.password': 'Неверный пароль',
    'day.details': 'Детали Дня',
    'close': 'Закрыть',
    'hours': 'часы',
    'task': 'Задача',
    'duration': 'Продолжительность',
    'description': 'Описание',
    'client': 'Клиент',
    'start.time': 'Время Начала',
    'end.time': 'Время Окончания'
  },
  zh: {
    'welcome.title': '欢迎使用 TimeTracker',
    'welcome.hero.title': '项目完全透明',
    'welcome.hero.subtitle': '查看 SolidTime 项目活动的独立界面',
    'welcome.hero.description': '这个应用程序是 SolidTime 的独立倡议。这是一个页面/应用程序，旨在为客户透明化项目活动。',
    'welcome.features.title': '主要功能',
    'welcome.about.title': '关于项目',
    'welcome.about.description': '这是一个独立界面，旨在为客户提供项目活动的完全透明性。',
    'welcome.about.solidtime': '基于 SolidTime，它提供了项目进度的清晰有序视图。',
    'welcome.footer': 'SolidTime 的独立界面 - 项目透明度',
    'get.started': '开始',
    'feature.transparency.title': '完全透明',
    'feature.transparency.description': '项目活动的完全可见性',
    'feature.timetracking.title': '时间跟踪',
    'feature.timetracking.description': '精确跟踪花费的时间',
    'feature.analytics.title': '详细分析',
    'feature.analytics.description': '性能报告和指标',
    'feature.clients.title': '客户门户',
    'feature.clients.description': '专用客户界面',
    'feature.security.title': '安全性',
    'feature.security.description': '保证数据保护',
    'feature.realtime.title': '实时',
    'feature.realtime.description': '即时更新',
    'projects': '项目',
    'logout': '登出',
    'setup.title': '设置',
    'setup.description': '配置您的连接',
    'setup.url.label': 'SolidTime URL',
    'setup.url.placeholder': 'https://app.solidtime.io',
    'setup.token.label': 'API 令牌',
    'setup.token.placeholder': '您的 API 令牌',
    'save': '保存',
    'cancel': '取消',
    'loading': '加载中...',
    'error.generic': '发生错误',
    'error.retry': '重试',
    'no.projects': '未找到项目',
    'no.activity': '未找到活动',
    'time.entries.title': '时间条目',
    'time.entries.subtitle': '查看所有项目时间条目',
    'time.entries.back': '返回项目',
    'total.hours': '总小时数',
    'days.with.records': '有记录的天数',
    'total.records': '总记录数',
    'activity.development': '活动开发',
    'activity.timeline': '时间轴',
    'project.details': '项目详情',
    'project.overview': '概览',
    'view.time.entries': '查看时间条目',
    'daily.hours': '每日小时',
    'weekly.overview': '每周概览',
    'team.activity': '团队活动',
    'latest.tasks': '最新任务',
    'enter.password': '输入密码',
    'password': '密码',
    'access.project': '访问项目',
    'invalid.password': '密码无效',
    'day.details': '日期详情',
    'close': '关闭',
    'hours': '小时',
    'task': '任务',
    'duration': '持续时间',
    'description': '描述',
    'client': '客户',
    'start.time': '开始时间',
    'end.time': '结束时间'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.split('-')[0].toLowerCase();
  const supportedLangs: Language[] = ['pt', 'en', 'es', 'fr', 'de', 'ru', 'zh'];
  
  if (supportedLangs.includes(browserLang as Language)) {
    return browserLang as Language;
  }
  
  return 'en'; // fallback to English
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang && ['pt', 'en', 'es', 'fr', 'de', 'ru', 'zh'].includes(savedLang)) {
      return savedLang as Language;
    }
    return detectBrowserLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (!savedLang) {
      const detectedLang = detectBrowserLanguage();
      setLanguage(detectedLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
