import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'app.title': 'Time Tracker',
    'app.subtitle': 'Track your time efficiently',
    'app.addon.description': 'Simple time tracking for teams',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Simple Time Tracking for Teams',
    'welcome.hero.subtitle': 'Track time, manage projects, and analyze productivity with ease.',
    'welcome.hero.description': 'This open-source time tracker helps teams monitor project hours, track progress, and improve productivity.',
    'welcome.features.title': 'Key Features',
    'welcome.about.title': 'About This App',
    'welcome.about.description': 'This time tracking application is designed to be simple, efficient, and transparent. It helps teams track their time and manage projects effectively.',
    'welcome.about.solidtime': 'Built on the solidtime platform, this app provides reliable time tracking capabilities for teams of all sizes.',
    'welcome.footer': '© 2023 Time Tracker. All rights reserved.',
    'get.started': 'Get Started',
    'setup.title': 'Setup Your Account',
    'setup.subtitle': 'Configure your time tracking settings',
    'setup.api.url.label': 'API Base URL',
    'setup.api.url.placeholder': 'https://api.example.com',
    'setup.token.label': 'Bearer Token',
    'setup.token.placeholder': 'Enter your API token',
    'setup.organization.label': 'Organization ID',
    'setup.organization.placeholder': 'Enter your organization ID',
    'setup.save': 'Save Configuration',
    'setup.saving': 'Saving...',
    'setup.error.fields': 'All fields are required',
    'setup.error.save': 'Failed to save configuration',
    'feature.transparency.title': 'Full Transparency',
    'feature.transparency.description': 'See exactly where time is being spent across all projects and team members.',
    'feature.timetracking.title': 'Simple Time Tracking',
    'feature.timetracking.description': 'Track time with minimal effort using our intuitive interface.',
    'feature.analytics.title': 'Detailed Analytics',
    'feature.analytics.description': 'Get insights into productivity patterns and project progress.',
    'feature.clients.title': 'Client Management',
    'feature.clients.description': 'Organize projects by client and share reports easily.',
    'feature.security.title': 'Secure Data',
    'feature.security.description': 'Your time tracking data is encrypted and securely stored.',
    'feature.realtime.title': 'Real-time Updates',
    'feature.realtime.description': 'See changes from your team in real-time as they happen.',
    'language.english': 'English',
    'language.portuguese': 'Portuguese',
    'language.spanish': 'Spanish',
    'language.french': 'French',
    'language.german': 'German',
    'language.italian': 'Italian',
    'language.chinese': 'Chinese',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'config.link.generator.title': 'Configuration Link Generator',
    'config.link.generator.subtitle': 'Create a shareable configuration link',
    'config.link.generate': 'Generate Link',
    'config.link.clear': 'Clear Form',
    'config.link.copied': 'Link Copied',
    'config.link.copied.description': 'Configuration link copied to clipboard',
    'config.link.error.copy': 'Failed to copy link',
    'config.link.generated': 'Link generated successfully',
    'config.link.result': 'Configuration Link',
    'config.link.instructions.title': 'How to use this link',
    'config.link.instructions.step1': 'Generate a link with your configuration details',
    'config.link.instructions.step2': 'Share the link with team members',
    'config.link.instructions.step3': 'When they open the link, their app will be automatically configured',
    'footer.powered.by': 'Powered by',
    'footer.open.source': 'Open Source Time Tracking',
    'footer.github': 'GitHub',
    'footer.docs': 'Documentation',
  },
  pt: {
    'app.title': 'Controle de Tempo',
    'app.subtitle': 'Controle seu tempo com eficiência',
    'app.addon.description': 'Controle de tempo simples para equipes',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Controle de Tempo Simples para Equipes',
    'welcome.hero.subtitle': 'Controle o tempo, gerencie projetos e analise a produtividade com facilidade.',
    'welcome.hero.description': 'Este controle de tempo de código aberto ajuda as equipes a monitorar as horas do projeto, acompanhar o progresso e melhorar a produtividade.',
    'welcome.features.title': 'Principais Recursos',
    'welcome.about.title': 'Sobre Este Aplicativo',
    'welcome.about.description': 'Este aplicativo de controle de tempo foi projetado para ser simples, eficiente e transparente. Ele ajuda as equipes a controlar seu tempo e gerenciar projetos de forma eficaz.',
    'welcome.about.solidtime': 'Construído na plataforma solidtime, este aplicativo fornece recursos confiáveis de controle de tempo para equipes de todos os tamanhos.',
    'welcome.footer': '© 2023 Controle de Tempo. Todos os direitos reservados.',
    'get.started': 'Começar',
    'setup.title': 'Configure Sua Conta',
    'setup.subtitle': 'Configure suas definições de controle de tempo',
    'setup.api.url.label': 'URL Base da API',
    'setup.api.url.placeholder': 'https://api.exemplo.com',
    'setup.token.label': 'Token de Acesso',
    'setup.token.placeholder': 'Digite seu token de API',
    'setup.organization.label': 'ID da Organização',
    'setup.organization.placeholder': 'Digite o ID da sua organização',
    'setup.save': 'Salvar Configuração',
    'setup.saving': 'Salvando...',
    'setup.error.fields': 'Todos os campos são obrigatórios',
    'setup.error.save': 'Falha ao salvar configuração',
    'feature.transparency.title': 'Transparência Total',
    'feature.transparency.description': 'Veja exatamente onde o tempo está sendo gasto em todos os projetos e membros da equipe.',
    'feature.timetracking.title': 'Controle de Tempo Simples',
    'feature.timetracking.description': 'Controle o tempo com o mínimo de esforço usando nossa interface intuitiva.',
    'feature.analytics.title': 'Análises Detalhadas',
    'feature.analytics.description': 'Obtenha insights sobre padrões de produtividade e progresso do projeto.',
    'feature.clients.title': 'Gestão de Clientes',
    'feature.clients.description': 'Organize projetos por cliente e compartilhe relatórios facilmente.',
    'feature.security.title': 'Dados Seguros',
    'feature.security.description': 'Seus dados de controle de tempo são criptografados e armazenados com segurança.',
    'feature.realtime.title': 'Atualizações em Tempo Real',
    'feature.realtime.description': 'Veja as alterações da sua equipe em tempo real conforme acontecem.',
    'language.english': 'Inglês',
    'language.portuguese': 'Português',
    'language.spanish': 'Espanhol',
    'language.french': 'Francês',
    'language.german': 'Alemão',
    'language.italian': 'Italiano',
    'language.chinese': 'Chinês',
    'theme.light': 'Claro',
    'theme.dark': 'Escuro',
    'theme.system': 'Sistema',
    'config.link.generator.title': 'Gerador de Link de Configuração',
    'config.link.generator.subtitle': 'Crie um link de configuração compartilhável',
    'config.link.generate': 'Gerar Link',
    'config.link.clear': 'Limpar Formulário',
    'config.link.copied': 'Link Copiado',
    'config.link.copied.description': 'Link de configuração copiado para a área de transferência',
    'config.link.error.copy': 'Falha ao copiar link',
    'config.link.generated': 'Link gerado com sucesso',
    'config.link.result': 'Link de Configuração',
    'config.link.instructions.title': 'Como usar este link',
    'config.link.instructions.step1': 'Gere um link com seus detalhes de configuração',
    'config.link.instructions.step2': 'Compartilhe o link com os membros da equipe',
    'config.link.instructions.step3': 'Quando eles abrirem o link, o aplicativo será configurado automaticamente',
    'footer.powered.by': 'Desenvolvido por',
    'footer.open.source': 'Controle de Tempo Open Source',
    'footer.github': 'GitHub',
    'footer.docs': 'Documentação',
  },
  es: {
    'app.title': 'Control de Tiempo',
    'app.subtitle': 'Controla tu tiempo de manera eficiente',
    'app.addon.description': 'Control de tiempo simple para equipos',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Control de Tiempo Simple para Equipos',
    'welcome.hero.subtitle': 'Controla el tiempo, gestiona proyectos y analiza la productividad con facilidad.',
    'welcome.hero.description': 'Este control de tiempo de código abierto ayuda a los equipos a monitorear las horas del proyecto, seguir el progreso y mejorar la productividad.',
    'welcome.features.title': 'Características Principales',
    'welcome.about.title': 'Acerca de Esta Aplicación',
    'welcome.about.description': 'Esta aplicación de control de tiempo está diseñada para ser simple, eficiente y transparente. Ayuda a los equipos a controlar su tiempo y gestionar proyectos de manera efectiva.',
    'welcome.about.solidtime': 'Construido en la plataforma solidtime, esta aplicación proporciona capacidades confiables de control de tiempo para equipos de todos los tamaños.',
    'welcome.footer': '© 2023 Control de Tiempo. Todos los derechos reservados.',
    'get.started': 'Comenzar',
    'setup.title': 'Configura Tu Cuenta',
    'setup.subtitle': 'Configura tus ajustes de control de tiempo',
    'setup.api.url.label': 'URL Base de la API',
    'setup.api.url.placeholder': 'https://api.ejemplo.com',
    'setup.token.label': 'Token de Acceso',
    'setup.token.placeholder': 'Ingresa tu token de API',
    'setup.organization.label': 'ID de la Organización',
    'setup.organization.placeholder': 'Ingresa el ID de tu organización',
    'setup.save': 'Guardar Configuración',
    'setup.saving': 'Guardando...',
    'setup.error.fields': 'Todos los campos son obligatorios',
    'setup.error.save': 'Error al guardar la configuración',
    'feature.transparency.title': 'Transparencia Total',
    'feature.transparency.description': 'Ve exactamente dónde se está gastando el tiempo en todos los proyectos y miembros del equipo.',
    'feature.timetracking.title': 'Control de Tiempo Simple',
    'feature.timetracking.description': 'Controla el tiempo con un mínimo esfuerzo usando nuestra interfaz intuitiva.',
    'feature.analytics.title': 'Análisis Detallados',
    'feature.analytics.description': 'Obtén información sobre patrones de productividad y progreso del proyecto.',
    'feature.clients.title': 'Gestión de Clientes',
    'feature.clients.description': 'Organiza proyectos por cliente y comparte informes fácilmente.',
    'feature.security.title': 'Datos Seguros',
    'feature.security.description': 'Tus datos de control de tiempo están encriptados y almacenados de forma segura.',
    'feature.realtime.title': 'Actualizaciones en Tiempo Real',
    'feature.realtime.description': 'Ve los cambios de tu equipo en tiempo real a medida que ocurren.',
    'language.english': 'Inglés',
    'language.portuguese': 'Portugués',
    'language.spanish': 'Español',
    'language.french': 'Francés',
    'language.german': 'Alemán',
    'language.italian': 'Italiano',
    'language.chinese': 'Chino',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Sistema',
    'config.link.generator.title': 'Generador de Enlaces de Configuración',
    'config.link.generator.subtitle': 'Crea un enlace de configuración compartible',
    'config.link.generate': 'Generar Enlace',
    'config.link.clear': 'Limpiar Formulario',
    'config.link.copied': 'Enlace Copiado',
    'config.link.copied.description': 'Enlace de configuración copiado al portapapeles',
    'config.link.error.copy': 'Error al copiar enlace',
    'config.link.generated': 'Enlace generado con éxito',
    'config.link.result': 'Enlace de Configuración',
    'config.link.instructions.title': 'Cómo usar este enlace',
    'config.link.instructions.step1': 'Genera un enlace con tus detalles de configuración',
    'config.link.instructions.step2': 'Comparte el enlace con los miembros del equipo',
    'config.link.instructions.step3': 'Cuando abran el enlace, su aplicación se configurará automáticamente',
    'footer.powered.by': 'Desarrollado por',
    'footer.open.source': 'Control de Tiempo de Código Abierto',
    'footer.github': 'GitHub',
    'footer.docs': 'Documentación',
  },
  fr: {
    'app.title': 'Suivi du Temps',
    'app.subtitle': 'Suivez votre temps efficacement',
    'app.addon.description': 'Suivi du temps simple pour les équipes',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Suivi du Temps Simple pour les Équipes',
    'welcome.hero.subtitle': 'Suivez le temps, gérez les projets et analysez la productivité facilement.',
    'welcome.hero.description': 'Ce suivi du temps open source aide les équipes à surveiller les heures de projet, suivre les progrès et améliorer la productivité.',
    'welcome.features.title': 'Fonctionnalités Clés',
    'welcome.about.title': 'À Propos de Cette Application',
    'welcome.about.description': 'Cette application de suivi du temps est conçue pour être simple, efficace et transparente. Elle aide les équipes à suivre leur temps et à gérer efficacement les projets.',
    'welcome.about.solidtime': 'Construit sur la plateforme solidtime, cette application fournit des capacités fiables de suivi du temps pour les équipes de toutes tailles.',
    'welcome.footer': '© 2023 Suivi du Temps. Tous droits réservés.',
    'get.started': 'Commencer',
    'setup.title': 'Configurez Votre Compte',
    'setup.subtitle': 'Configurez vos paramètres de suivi du temps',
    'setup.api.url.label': 'URL de Base de l\'API',
    'setup.api.url.placeholder': 'https://api.exemple.com',
    'setup.token.label': 'Jeton d\'Accès',
    'setup.token.placeholder': 'Entrez votre jeton d\'API',
    'setup.organization.label': 'ID de l\'Organisation',
    'setup.organization.placeholder': 'Entrez l\'ID de votre organisation',
    'setup.save': 'Enregistrer la Configuration',
    'setup.saving': 'Enregistrement...',
    'setup.error.fields': 'Tous les champs sont obligatoires',
    'setup.error.save': 'Échec de l\'enregistrement de la configuration',
    'feature.transparency.title': 'Transparence Totale',
    'feature.transparency.description': 'Voyez exactement où le temps est dépensé dans tous les projets et membres de l\'équipe.',
    'feature.timetracking.title': 'Suivi du Temps Simple',
    'feature.timetracking.description': 'Suivez le temps avec un minimum d\'effort grâce à notre interface intuitive.',
    'feature.analytics.title': 'Analyses Détaillées',
    'feature.analytics.description': 'Obtenez des informations sur les modèles de productivité et l\'avancement du projet.',
    'feature.clients.title': 'Gestion des Clients',
    'feature.clients.description': 'Organisez les projets par client et partagez facilement des rapports.',
    'feature.security.title': 'Données Sécurisées',
    'feature.security.description': 'Vos données de suivi du temps sont cryptées et stockées en toute sécurité.',
    'feature.realtime.title': 'Mises à Jour en Temps Réel',
    'feature.realtime.description': 'Voyez les changements de votre équipe en temps réel au fur et à mesure qu\'ils se produisent.',
    'language.english': 'Anglais',
    'language.portuguese': 'Portugais',
    'language.spanish': 'Espagnol',
    'language.french': 'Français',
    'language.german': 'Allemand',
    'language.italian': 'Italien',
    'language.chinese': 'Chinois',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.system': 'Système',
    'config.link.generator.title': 'Générateur de Liens de Configuration',
    'config.link.generator.subtitle': 'Créez un lien de configuration partageable',
    'config.link.generate': 'Générer un Lien',
    'config.link.clear': 'Effacer le Formulaire',
    'config.link.copied': 'Lien Copié',
    'config.link.copied.description': 'Lien de configuration copié dans le presse-papiers',
    'config.link.error.copy': 'Échec de la copie du lien',
    'config.link.generated': 'Lien généré avec succès',
    'config.link.result': 'Lien de Configuration',
    'config.link.instructions.title': 'Comment utiliser ce lien',
    'config.link.instructions.step1': 'Générez un lien avec vos détails de configuration',
    'config.link.instructions.step2': 'Partagez le lien avec les membres de l\'équipe',
    'config.link.instructions.step3': 'Lorsqu\'ils ouvrent le lien, leur application sera automatiquement configurée',
    'footer.powered.by': 'Propulsé par',
    'footer.open.source': 'Suivi du temps Open Source',
    'footer.github': 'GitHub',
    'footer.docs': 'Documentation',
  },
  de: {
    'app.title': 'Zeiterfassung',
    'app.subtitle': 'Erfassen Sie Ihre Zeit effizient',
    'app.addon.description': 'Einfache Zeiterfassung für Teams',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Einfache Zeiterfassung für Teams',
    'welcome.hero.subtitle': 'Erfassen Sie Zeit, verwalten Sie Projekte und analysieren Sie die Produktivität mit Leichtigkeit.',
    'welcome.hero.description': 'Diese Open-Source-Zeiterfassung hilft Teams, Projektstunden zu überwachen, Fortschritte zu verfolgen und die Produktivität zu verbessern.',
    'welcome.features.title': 'Hauptfunktionen',
    'welcome.about.title': 'Über Diese Anwendung',
    'welcome.about.description': 'Diese Zeiterfassungsanwendung ist darauf ausgelegt, einfach, effizient und transparent zu sein. Sie hilft Teams, ihre Zeit zu erfassen und Projekte effektiv zu verwalten.',
    'welcome.about.solidtime': 'Aufgebaut auf der solidtime-Plattform bietet diese App zuverlässige Zeiterfassungsfunktionen für Teams aller Größen.',
    'welcome.footer': '© 2023 Zeiterfassung. Alle Rechte vorbehalten.',
    'get.started': 'Loslegen',
    'setup.title': 'Konto Einrichten',
    'setup.subtitle': 'Konfigurieren Sie Ihre Zeiterfassungseinstellungen',
    'setup.api.url.label': 'API-Basis-URL',
    'setup.api.url.placeholder': 'https://api.beispiel.com',
    'setup.token.label': 'Zugriffstoken',
    'setup.token.placeholder': 'Geben Sie Ihren API-Token ein',
    'setup.organization.label': 'Organisations-ID',
    'setup.organization.placeholder': 'Geben Sie Ihre Organisations-ID ein',
    'setup.save': 'Konfiguration Speichern',
    'setup.saving': 'Speichern...',
    'setup.error.fields': 'Alle Felder sind erforderlich',
    'setup.error.save': 'Fehler beim Speichern der Konfiguration',
    'feature.transparency.title': 'Volle Transparenz',
    'feature.transparency.description': 'Sehen Sie genau, wo Zeit in allen Projekten und Teammitgliedern verbracht wird.',
    'feature.timetracking.title': 'Einfache Zeiterfassung',
    'feature.timetracking.description': 'Erfassen Sie Zeit mit minimalem Aufwand mit unserer intuitiven Oberfläche.',
    'feature.analytics.title': 'Detaillierte Analysen',
    'feature.analytics.description': 'Erhalten Sie Einblicke in Produktivitätsmuster und Projektfortschritte.',
    'feature.clients.title': 'Kundenverwaltung',
    'feature.clients.description': 'Organisieren Sie Projekte nach Kunden und teilen Sie Berichte einfach.',
    'feature.security.title': 'Sichere Daten',
    'feature.security.description': 'Ihre Zeiterfassungsdaten werden verschlüsselt und sicher gespeichert.',
    'feature.realtime.title': 'Echtzeit-Updates',
    'feature.realtime.description': 'Sehen Sie Änderungen Ihres Teams in Echtzeit, während sie passieren.',
    'language.english': 'Englisch',
    'language.portuguese': 'Portugiesisch',
    'language.spanish': 'Spanisch',
    'language.french': 'Französisch',
    'language.german': 'Deutsch',
    'language.italian': 'Italienisch',
    'language.chinese': 'Chinesisch',
    'theme.light': 'Hell',
    'theme.dark': 'Dunkel',
    'theme.system': 'System',
    'config.link.generator.title': 'Konfigurations-Link-Generator',
    'config.link.generator.subtitle': 'Erstellen Sie einen teilbaren Konfigurationslink',
    'config.link.generate': 'Link Generieren',
    'config.link.clear': 'Formular Löschen',
    'config.link.copied': 'Link Kopiert',
    'config.link.copied.description': 'Konfigurationslink in die Zwischenablage kopiert',
    'config.link.error.copy': 'Fehler beim Kopieren des Links',
    'config.link.generated': 'Link erfolgreich generiert',
    'config.link.result': 'Konfigurationslink',
    'config.link.instructions.title': 'Wie man diesen Link verwendet',
    'config.link.instructions.step1': 'Generieren Sie einen Link mit Ihren Konfigurationsdetails',
    'config.link.instructions.step2': 'Teilen Sie den Link mit Teammitgliedern',
    'config.link.instructions.step3': 'Wenn sie den Link öffnen, wird ihre App automatisch konfiguriert',
    'footer.powered.by': 'Angetrieben von',
    'footer.open.source': 'Open Source Zeiterfassung',
    'footer.github': 'GitHub',
    'footer.docs': 'Dokumentation',
  },
  it: {
    'app.title': 'Tracciamento del Tempo',
    'app.subtitle': 'Traccia il tuo tempo in modo efficiente',
    'app.addon.description': 'Tracciamento del tempo semplice per team',
    'app.github': 'GitHub',
    'welcome.hero.title': 'Tracciamento del Tempo Semplice per Team',
    'welcome.hero.subtitle': 'Traccia il tempo, gestisci progetti e analizza la produttività con facilità.',
    'welcome.hero.description': 'Questo tracciatore del tempo open source aiuta i team a monitorare le ore di progetto, tracciare i progressi e migliorare la produttività.',
    'welcome.features.title': 'Funzionalità Principali',
    'welcome.about.title': 'Informazioni su Questa Applicazione',
    'welcome.about.description': 'Questa applicazione di tracciamento del tempo è progettata per essere semplice, efficiente e trasparente. Aiuta i team a tracciare il loro tempo e gestire i progetti in modo efficace.',
    'welcome.about.solidtime': 'Costruito sulla piattaforma solidtime, questa app fornisce capacità affidabili di tracciamento del tempo per team di tutte le dimensioni.',
    'welcome.footer': '© 2023 Tracciamento del Tempo. Tutti i diritti riservati.',
    'get.started': 'Inizia',
    'setup.title': 'Configura il Tuo Account',
    'setup.subtitle': 'Configura le tue impostazioni di tracciamento del tempo',
    'setup.api.url.label': 'URL Base API',
    'setup.api.url.placeholder': 'https://api.esempio.com',
    'setup.token.label': 'Token di Accesso',
    'setup.token.placeholder': 'Inserisci il tuo token API',
    'setup.organization.label': 'ID Organizzazione',
    'setup.organization.placeholder': 'Inserisci l\'ID della tua organizzazione',
    'setup.save': 'Salva Configurazione',
    'setup.saving': 'Salvataggio...',
    'setup.error.fields': 'Tutti i campi sono obbligatori',
    'setup.error.save': 'Impossibile salvare la configurazione',
    'feature.transparency.title': 'Piena Trasparenza',
    'feature.transparency.description': 'Vedi esattamente dove viene speso il tempo in tutti i progetti e membri del team.',
    'feature.timetracking.title': 'Tracciamento del Tempo Semplice',
    'feature.timetracking.description': 'Traccia il tempo con il minimo sforzo utilizzando la nostra interfaccia intuitiva.',
    'feature.analytics.title': 'Analisi Dettagliate',
    'feature.analytics.description': 'Ottieni informazioni sui modelli di produttività e sui progressi del progetto.',
    'feature.clients.title': 'Gestione dei Clienti',
    'feature.clients.description': 'Organizza i progetti per cliente e condividi facilmente i report.',
    'feature.security.title': 'Dati Sicuri',
    'feature.security.description': 'I tuoi dati di tracciamento del tempo sono crittografati e archiviati in modo sicuro.',
    'feature.realtime.title': 'Aggiornamenti in Tempo Reale',
    'feature.realtime.description': 'Vedi i cambiamenti del tuo team in tempo reale mentre avvengono.',
    'language.english': 'Inglese',
    'language.portuguese': 'Portoghese',
    'language.spanish': 'Spagnolo',
    'language.french': 'Francese',
    'language.german': 'Tedesco',
    'language.italian': 'Italiano',
    'language.chinese': 'Cinese',
    'theme.light': 'Chiaro',
    'theme.dark': 'Scuro',
    'theme.system': 'Sistema',
    'config.link.generator.title': 'Generatore di Link di Configurazione',
    'config.link.generator.subtitle': 'Crea un link di configurazione condivisibile',
    'config.link.generate': 'Genera Link',
    'config.link.clear': 'Cancella Modulo',
    'config.link.copied': 'Link Copiato',
    'config.link.copied.description': 'Link di configurazione copiato negli appunti',
    'config.link.error.copy': 'Impossibile copiare il link',
    'config.link.generated': 'Link generato con successo',
    'config.link.result': 'Link di Configurazione',
    'config.link.instructions.title': 'Come usare questo link',
    'config.link.instructions.step1': 'Genera un link con i tuoi dettagli di configurazione',
    'config.link.instructions.step2': 'Condividi il link con i membri del team',
    'config.link.instructions.step3': 'Quando aprono il link, la loro app verrà configurata automaticamente',
    'footer.powered.by': 'Alimentato da',
    'footer.open.source': 'Tracciamento del tempo Open Source',
    'footer.github': 'GitHub',
    'footer.docs': 'Documentazione',
  },
  zh: {
    'app.title': '时间跟踪',
    'app.subtitle': '高效跟踪您的时间',
    'app.addon.description': '团队简单时间跟踪',
    'app.github': 'GitHub',
    'welcome.hero.title': '团队简单时间跟踪',
    'welcome.hero.subtitle': '轻松跟踪时间、管理项目和分析生产力。',
    'welcome.hero.description': '这个开源时间跟踪器帮助团队监控项目小时数、跟踪进度和提高生产力。',
    'welcome.features.title': '主要功能',
    'welcome.about.title': '关于此应用',
    'welcome.about.description': '这个时间跟踪应用程序设计简单、高效和透明。它帮助团队有效地跟踪时间和管理项目。',
    'welcome.about.solidtime': '基于solidtime平台构建，此应用为各种规模的团队提供可靠的时间跟踪功能。',
    'welcome.footer': '© 2023 时间跟踪。保留所有权利。',
    'get.started': '开始使用',
    'setup.title': '设置您的账户',
    'setup.subtitle': '配置您的时间跟踪设置',
    'setup.api.url.label': 'API基础URL',
    'setup.api.url.placeholder': 'https://api.example.com',
    'setup.token.label': '访问令牌',
    'setup.token.placeholder': '输入您的API令牌',
    'setup.organization.label': '组织ID',
    'setup.organization.placeholder': '输入您的组织ID',
    'setup.save': '保存配置',
    'setup.saving': '保存中...',
    'setup.error.fields': '所有字段都是必需的',
    'setup.error.save': '保存配置失败',
    'feature.transparency.title': '完全透明',
    'feature.transparency.description': '准确了解所有项目和团队成员的时间花费情况。',
    'feature.timetracking.title': '简单时间跟踪',
    'feature.timetracking.description': '使用我们直观的界面轻松跟踪时间。',
    'feature.analytics.title': '详细分析',
    'feature.analytics.description': '获取有关生产力模式和项目进度的见解。',
    'feature.clients.title': '客户管理',
    'feature.clients.description': '按客户组织项目并轻松共享报告。',
    'feature.security.title': '安全数据',
    'feature.security.description': '您的时间跟踪数据经过加密并安全存储。',
    'feature.realtime.title': '实时更新',
    'feature.realtime.description': '实时查看团队的变化。',
    'language.english': '英语',
    'language.portuguese': '葡萄牙语',
    'language.spanish': '西班牙语',
    'language.french': '法语',
    'language.german': '德语',
    'language.italian': '意大利语',
    'language.chinese': '中文',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.system': '系统',
    'config.link.generator.title': '配置链接生成器',
    'config.link.generator.subtitle': '创建可共享的配置链接',
    'config.link.generate': '生成链接',
    'config.link.clear': '清除表单',
    'config.link.copied': '链接已复制',
    'config.link.copied.description': '配置链接已复制到剪贴板',
    'config.link.error.copy': '复制链接失败',
    'config.link.generated': '链接生成成功',
    'config.link.result': '配置链接',
    'config.link.instructions.title': '如何使用此链接',
    'config.link.instructions.step1': '使用您的配置详细信息生成链接',
    'config.link.instructions.step2': '与团队成员共享链接',
    'config.link.instructions.step3': '当他们打开链接时，他们的应用程序将自动配置',
    'footer.powered.by': '技术支持',
    'footer.open.source': '开源时间跟踪',
    'footer.github': 'GitHub',
    'footer.docs': '文档',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || navigator.language.split('-')[0] || 'en';
  });

  const t = (key: string): string => {
    const lang = language in translations ? language : 'en';
    return translations[lang as keyof typeof translations][key as keyof typeof translations[keyof typeof translations]] || key;
  };

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
