import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt' | 'es' | 'fr' | 'de' | 'it' | 'ja';

interface LanguageContextProps {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translations = {
  en: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Your time tracking companion',
    'app.github': 'GitHub',
    'loading': 'Loading...',
    'welcome.hero.title': 'Welcome to TimeTracker',
    'welcome.hero.subtitle': 'Track your time efficiently and transparently',
    'welcome.hero.description': 'Manage your projects and clients with ease.',
    'setup.title': 'Setup',
    'setup.subtitle': 'Configure your API credentials',
    'setup.api.url.label': 'API Base URL',
    'setup.api.url.placeholder': 'https://api.example.com',
    'setup.token.label': 'Bearer Token',
    'setup.token.placeholder': 'Enter your bearer token',
    'setup.organization.label': 'Organization ID',
    'setup.organization.placeholder': 'Enter your organization ID',
    'setup.error.fields': 'Please fill in all fields.',
    'setup.error.save': 'Failed to save configuration.',
    'setup.validating': 'Validating credentials...',
    'setup.error.invalid.token': 'Invalid bearer token. Please check your token.',
    'setup.error.invalid.organization': 'Invalid organization ID. Please check your organization ID.',
    'setup.error.invalid.credentials': 'Invalid credentials. Please check your API URL, token, and organization ID.',
    'get.started': 'Get Started',
    'config.link.generator.title': 'Config Link Generator',
    'config.link.generator.subtitle': 'Generate configuration links easily',
    'projects': 'Projects',
    'config.required': 'Configuration Required',
    'config.required.message': 'Please configure your API credentials to continue.',
    'welcome.features.title': 'Features',
    'feature.transparency.title': 'Transparency',
    'feature.transparency.description': 'See exactly where your time goes.',
    'feature.timetracking.title': 'Time Tracking',
    'feature.timetracking.description': 'Track your work hours effortlessly.',
    'feature.analytics.title': 'Analytics',
    'feature.analytics.description': 'Gain insights from your data.',
    'feature.clients.title': 'Clients',
    'feature.clients.description': 'Manage your clients efficiently.',
    'feature.security.title': 'Security',
    'feature.security.description': 'Your data is safe with us.',
    'feature.realtime.title': 'Real-time Updates',
    'feature.realtime.description': 'Stay updated with live data.',
    'welcome.about.title': 'About TimeTracker',
    'welcome.about.description': 'TimeTracker is designed to help you manage your time and projects effectively.',
    'welcome.about.solidtime': 'Powered by SolidTime',
    'footer.docs': 'Documentation',
  },
  pt: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Seu companheiro de rastreamento de tempo',
    'app.github': 'GitHub',
    'loading': 'Carregando...',
    'welcome.hero.title': 'Bem-vindo ao TimeTracker',
    'welcome.hero.subtitle': 'Rastreie seu tempo de forma eficiente e transparente',
    'welcome.hero.description': 'Gerencie seus projetos e clientes com facilidade.',
    'setup.title': 'Configuração',
    'setup.subtitle': 'Configure suas credenciais da API',
    'setup.api.url.label': 'URL Base da API',
    'setup.api.url.placeholder': 'https://api.exemplo.com',
    'setup.token.label': 'Token Bearer',
    'setup.token.placeholder': 'Insira seu token bearer',
    'setup.organization.label': 'ID da Organização',
    'setup.organization.placeholder': 'Insira o ID da sua organização',
    'setup.error.fields': 'Por favor, preencha todos os campos.',
    'setup.error.save': 'Falha ao salvar a configuração.',
    'setup.validating': 'Validando credenciais...',
    'setup.error.invalid.token': 'Token inválido. Por favor, verifique seu token.',
    'setup.error.invalid.organization': 'ID da organização inválido. Por favor, verifique o ID da sua organização.',
    'setup.error.invalid.credentials': 'Credenciais inválidas. Por favor, verifique sua URL da API, token e ID da organização.',
    'get.started': 'Começar',
    'config.link.generator.title': 'Gerador de Link de Configuração',
    'config.link.generator.subtitle': 'Gere links de configuração facilmente',
    'projects': 'Projetos',
    'config.required': 'Configuração Necessária',
    'config.required.message': 'Por favor, configure suas credenciais da API para continuar.',
    'welcome.features.title': 'Recursos',
    'feature.transparency.title': 'Transparência',
    'feature.transparency.description': 'Veja exatamente onde seu tempo é gasto.',
    'feature.timetracking.title': 'Rastreamento de Tempo',
    'feature.timetracking.description': 'Registre suas horas de trabalho facilmente.',
    'feature.analytics.title': 'Análises',
    'feature.analytics.description': 'Obtenha insights dos seus dados.',
    'feature.clients.title': 'Clientes',
    'feature.clients.description': 'Gerencie seus clientes eficientemente.',
    'feature.security.title': 'Segurança',
    'feature.security.description': 'Seus dados estão seguros conosco.',
    'feature.realtime.title': 'Atualizações em Tempo Real',
    'feature.realtime.description': 'Fique atualizado com dados ao vivo.',
    'welcome.about.title': 'Sobre o TimeTracker',
    'welcome.about.description': 'O TimeTracker foi projetado para ajudar você a gerenciar seu tempo e projetos de forma eficaz.',
    'welcome.about.solidtime': 'Desenvolvido por SolidTime',
    'footer.docs': 'Documentação',
  },
  es: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Tu compañero para el seguimiento del tiempo',
    'app.github': 'GitHub',
    'loading': 'Cargando...',
    'welcome.hero.title': 'Bienvenido a TimeTracker',
    'welcome.hero.subtitle': 'Rastrea tu tiempo de manera eficiente y transparente',
    'welcome.hero.description': 'Gestiona tus proyectos y clientes con facilidad.',
    'setup.title': 'Configuración',
    'setup.subtitle': 'Configura tus credenciales de API',
    'setup.api.url.label': 'URL Base de la API',
    'setup.api.url.placeholder': 'https://api.ejemplo.com',
    'setup.token.label': 'Token Bearer',
    'setup.token.placeholder': 'Introduce tu token bearer',
    'setup.organization.label': 'ID de la Organización',
    'setup.organization.placeholder': 'Introduce el ID de tu organización',
    'setup.error.fields': 'Por favor, completa todos los campos.',
    'setup.error.save': 'Error al guardar la configuración.',
    'setup.validating': 'Validando credenciales...',
    'setup.error.invalid.token': 'Token inválido. Por favor, verifica tu token.',
    'setup.error.invalid.organization': 'ID de organización inválido. Por favor, verifica el ID de tu organización.',
    'setup.error.invalid.credentials': 'Credenciales inválidas. Por favor, verifica tu URL de API, token e ID de organización.',
    'get.started': 'Comenzar',
    'config.link.generator.title': 'Generador de Enlace de Configuración',
    'config.link.generator.subtitle': 'Genera enlaces de configuración fácilmente',
    'projects': 'Proyectos',
    'config.required': 'Configuración Requerida',
    'config.required.message': 'Por favor, configura tus credenciales de API para continuar.',
    'welcome.features.title': 'Características',
    'feature.transparency.title': 'Transparencia',
    'feature.transparency.description': 'Ve exactamente dónde va tu tiempo.',
    'feature.timetracking.title': 'Seguimiento de Tiempo',
    'feature.timetracking.description': 'Registra tus horas de trabajo sin esfuerzo.',
    'feature.analytics.title': 'Analíticas',
    'feature.analytics.description': 'Obtén información de tus datos.',
    'feature.clients.title': 'Clientes',
    'feature.clients.description': 'Gestiona tus clientes eficientemente.',
    'feature.security.title': 'Seguridad',
    'feature.security.description': 'Tus datos están seguros con nosotros.',
    'feature.realtime.title': 'Actualizaciones en Tiempo Real',
    'feature.realtime.description': 'Mantente actualizado con datos en vivo.',
    'welcome.about.title': 'Acerca de TimeTracker',
    'welcome.about.description': 'TimeTracker está diseñado para ayudarte a gestionar tu tiempo y proyectos eficazmente.',
    'welcome.about.solidtime': 'Desarrollado por SolidTime',
    'footer.docs': 'Documentación',
  },
  fr: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Votre compagnon de suivi du temps',
    'app.github': 'GitHub',
    'loading': 'Chargement...',
    'welcome.hero.title': 'Bienvenue sur TimeTracker',
    'welcome.hero.subtitle': 'Suivez votre temps efficacement et en toute transparence',
    'welcome.hero.description': 'Gérez vos projets et clients facilement.',
    'setup.title': 'Configuration',
    'setup.subtitle': 'Configurez vos identifiants API',
    'setup.api.url.label': 'URL de base de l\'API',
    'setup.api.url.placeholder': 'https://api.exemple.com',
    'setup.token.label': 'Token Bearer',
    'setup.token.placeholder': 'Entrez votre token bearer',
    'setup.organization.label': 'ID de l\'organisation',
    'setup.organization.placeholder': 'Entrez l\'ID de votre organisation',
    'setup.error.fields': 'Veuillez remplir tous les champs.',
    'setup.error.save': 'Échec de la sauvegarde de la configuration.',
    'setup.validating': 'Validation des identifiants...',
    'setup.error.invalid.token': 'Token invalide. Veuillez vérifier votre token.',
    'setup.error.invalid.organization': 'ID d\'organisation invalide. Veuillez vérifier l\'ID de votre organisation.',
    'setup.error.invalid.credentials': 'Identifiants invalides. Veuillez vérifier votre URL d\'API, token et ID d\'organisation.',
    'get.started': 'Commencer',
    'config.link.generator.title': 'Générateur de lien de configuration',
    'config.link.generator.subtitle': 'Générez facilement des liens de configuration',
    'projects': 'Projets',
    'config.required': 'Configuration requise',
    'config.required.message': 'Veuillez configurer vos identifiants API pour continuer.',
    'welcome.features.title': 'Fonctionnalités',
    'feature.transparency.title': 'Transparence',
    'feature.transparency.description': 'Voyez exactement où votre temps est passé.',
    'feature.timetracking.title': 'Suivi du temps',
    'feature.timetracking.description': 'Suivez vos heures de travail facilement.',
    'feature.analytics.title': 'Analytique',
    'feature.analytics.description': 'Obtenez des insights à partir de vos données.',
    'feature.clients.title': 'Clients',
    'feature.clients.description': 'Gérez vos clients efficacement.',
    'feature.security.title': 'Sécurité',
    'feature.security.description': 'Vos données sont en sécurité avec nous.',
    'feature.realtime.title': 'Mises à jour en temps réel',
    'feature.realtime.description': 'Restez à jour avec des données en direct.',
    'welcome.about.title': 'À propos de TimeTracker',
    'welcome.about.description': 'TimeTracker est conçu pour vous aider à gérer efficacement votre temps et vos projets.',
    'welcome.about.solidtime': 'Propulsé par SolidTime',
    'footer.docs': 'Documentation',
  },
  de: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Ihr Begleiter für die Zeiterfassung',
    'app.github': 'GitHub',
    'loading': 'Laden...',
    'welcome.hero.title': 'Willkommen bei TimeTracker',
    'welcome.hero.subtitle': 'Verfolgen Sie Ihre Zeit effizient und transparent',
    'welcome.hero.description': 'Verwalten Sie Ihre Projekte und Kunden mühelos.',
    'setup.title': 'Einrichtung',
    'setup.subtitle': 'Konfigurieren Sie Ihre API-Zugangsdaten',
    'setup.api.url.label': 'API-Basis-URL',
    'setup.api.url.placeholder': 'https://api.beispiel.com',
    'setup.token.label': 'Bearer-Token',
    'setup.token.placeholder': 'Geben Sie Ihr Bearer-Token ein',
    'setup.organization.label': 'Organisations-ID',
    'setup.organization.placeholder': 'Geben Sie Ihre Organisations-ID ein',
    'setup.error.fields': 'Bitte füllen Sie alle Felder aus.',
    'setup.error.save': 'Konfiguration konnte nicht gespeichert werden.',
    'setup.validating': 'Validierung der Zugangsdaten...',
    'setup.error.invalid.token': 'Ungültiges Bearer-Token. Bitte überprüfen Sie Ihr Token.',
    'setup.error.invalid.organization': 'Ungültige Organisations-ID. Bitte überprüfen Sie Ihre Organisations-ID.',
    'setup.error.invalid.credentials': 'Ungültige Zugangsdaten. Bitte überprüfen Sie Ihre API-URL, Token und Organisations-ID.',
    'get.started': 'Loslegen',
    'config.link.generator.title': 'Konfigurationslink-Generator',
    'config.link.generator.subtitle': 'Generieren Sie einfach Konfigurationslinks',
    'projects': 'Projekte',
    'config.required': 'Konfiguration erforderlich',
    'config.required.message': 'Bitte konfigurieren Sie Ihre API-Zugangsdaten, um fortzufahren.',
    'welcome.features.title': 'Funktionen',
    'feature.transparency.title': 'Transparenz',
    'feature.transparency.description': 'Sehen Sie genau, wo Ihre Zeit hingeht.',
    'feature.timetracking.title': 'Zeiterfassung',
    'feature.timetracking.description': 'Verfolgen Sie Ihre Arbeitsstunden mühelos.',
    'feature.analytics.title': 'Analytik',
    'feature.analytics.description': 'Gewinnen Sie Einblicke aus Ihren Daten.',
    'feature.clients.title': 'Kunden',
    'feature.clients.description': 'Verwalten Sie Ihre Kunden effizient.',
    'feature.security.title': 'Sicherheit',
    'feature.security.description': 'Ihre Daten sind bei uns sicher.',
    'feature.realtime.title': 'Echtzeit-Updates',
    'feature.realtime.description': 'Bleiben Sie mit Live-Daten auf dem Laufenden.',
    'welcome.about.title': 'Über TimeTracker',
    'welcome.about.description': 'TimeTracker wurde entwickelt, um Ihnen bei der effektiven Verwaltung Ihrer Zeit und Projekte zu helfen.',
    'welcome.about.solidtime': 'Angetrieben von SolidTime',
    'footer.docs': 'Dokumentation',
  },
  it: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'Il tuo compagno per il monitoraggio del tempo',
    'app.github': 'GitHub',
    'loading': 'Caricamento...',
    'welcome.hero.title': 'Benvenuto in TimeTracker',
    'welcome.hero.subtitle': 'Monitora il tuo tempo in modo efficiente e trasparente',
    'welcome.hero.description': 'Gestisci i tuoi progetti e clienti con facilità.',
    'setup.title': 'Configurazione',
    'setup.subtitle': 'Configura le tue credenziali API',
    'setup.api.url.label': 'URL Base API',
    'setup.api.url.placeholder': 'https://api.esempio.com',
    'setup.token.label': 'Token Bearer',
    'setup.token.placeholder': 'Inserisci il tuo token bearer',
    'setup.organization.label': 'ID Organizzazione',
    'setup.organization.placeholder': 'Inserisci l\'ID della tua organizzazione',
    'setup.error.fields': 'Per favore, compila tutti i campi.',
    'setup.error.save': 'Impossibile salvare la configurazione.',
    'setup.validating': 'Validazione credenziali...',
    'setup.error.invalid.token': 'Token non valido. Controlla il tuo token.',
    'setup.error.invalid.organization': 'ID organizzazione non valido. Controlla l\'ID della tua organizzazione.',
    'setup.error.invalid.credentials': 'Credenziali non valide. Controlla la tua URL API, token e ID organizzazione.',
    'get.started': 'Inizia',
    'config.link.generator.title': 'Generatore di link di configurazione',
    'config.link.generator.subtitle': 'Genera facilmente link di configurazione',
    'projects': 'Progetti',
    'config.required': 'Configurazione richiesta',
    'config.required.message': 'Per favore, configura le tue credenziali API per continuare.',
    'welcome.features.title': 'Caratteristiche',
    'feature.transparency.title': 'Trasparenza',
    'feature.transparency.description': 'Vedi esattamente dove va il tuo tempo.',
    'feature.timetracking.title': 'Monitoraggio del tempo',
    'feature.timetracking.description': 'Registra le tue ore di lavoro senza sforzo.',
    'feature.analytics.title': 'Analisi',
    'feature.analytics.description': 'Ottieni informazioni dai tuoi dati.',
    'feature.clients.title': 'Clienti',
    'feature.clients.description': 'Gestisci i tuoi clienti in modo efficiente.',
    'feature.security.title': 'Sicurezza',
    'feature.security.description': 'I tuoi dati sono al sicuro con noi.',
    'feature.realtime.title': 'Aggiornamenti in tempo reale',
    'feature.realtime.description': 'Rimani aggiornato con dati in tempo reale.',
    'welcome.about.title': 'Informazioni su TimeTracker',
    'welcome.about.description': 'TimeTracker è progettato per aiutarti a gestire efficacemente il tuo tempo e i tuoi progetti.',
    'welcome.about.solidtime': 'Powered by SolidTime',
    'footer.docs': 'Documentazione',
  },
  ja: {
    'app.title': 'TimeTracker',
    'app.addon.description': 'あなたの時間追跡パートナー',
    'app.github': 'GitHub',
    'loading': '読み込み中...',
    'welcome.hero.title': 'TimeTrackerへようこそ',
    'welcome.hero.subtitle': '効率的かつ透明性のある時間管理',
    'welcome.hero.description': 'プロジェクトとクライアントを簡単に管理。',
    'setup.title': 'セットアップ',
    'setup.subtitle': 'API認証情報を設定してください',
    'setup.api.url.label': 'APIベースURL',
    'setup.api.url.placeholder': 'https://api.example.com',
    'setup.token.label': 'ベアラートークン',
    'setup.token.placeholder': 'ベアラートークンを入力してください',
    'setup.organization.label': '組織ID',
    'setup.organization.placeholder': '組織IDを入力してください',
    'setup.error.fields': 'すべてのフィールドを入力してください。',
    'setup.error.save': '設定の保存に失敗しました。',
    'setup.validating': '認証情報を検証中...',
    'setup.error.invalid.token': '無効なベアラートークンです。トークンを確認してください。',
    'setup.error.invalid.organization': '無効な組織IDです。組織IDを確認してください。',
    'setup.error.invalid.credentials': '無効な認証情報です。API URL、トークン、組織IDを確認してください。',
    'get.started': '開始する',
    'config.link.generator.title': '設定リンクジェネレーター',
    'config.link.generator.subtitle': '簡単に設定リンクを生成',
    'projects': 'プロジェクト',
    'config.required': '設定が必要です',
    'config.required.message': '続行するにはAPI認証情報を設定してください。',
    'welcome.features.title': '機能',
    'feature.transparency.title': '透明性',
    'feature.transparency.description': '時間の使い道を正確に把握。',
    'feature.timetracking.title': '時間追跡',
    'feature.timetracking.description': '作業時間を簡単に記録。',
    'feature.analytics.title': '分析',
    'feature.analytics.description': 'データから洞察を得る。',
    'feature.clients.title': 'クライアント',
    'feature.clients.description': 'クライアントを効率的に管理。',
    'feature.security.title': 'セキュリティ',
    'feature.security.description': 'データは安全に保護されています。',
    'feature.realtime.title': 'リアルタイム更新',
    'feature.realtime.description': 'ライブデータで最新情報を取得。',
    'welcome.about.title': 'TimeTrackerについて',
    'welcome.about.description': 'TimeTrackerは時間とプロジェクトを効果的に管理するために設計されています。',
    'welcome.about.solidtime': 'SolidTimeによって提供されています',
    'footer.docs': 'ドキュメント',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextProps => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
