// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tudwlqbhbvgqmcebritd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZHdscWJoYnZncW1jZWJyaXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjMzODAsImV4cCI6MjA2MzUzOTM4MH0.ea-kT8WQlQ5iipFP7nnyylEG_jQ2xNl1reWhG1KVAx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);